### ISSUE TITLE
Setting runOnDemandStartTimeout or runOnDemandCloseAfter for a path causes segfault/panic in v1.2.0

### ISSUE THREAD

**Issue by mrlt8** [bluenviron/mediamtx#2529]
## Which version are you using?

v1.2.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [x] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Setting runOnDemandStartTimeout and/or runOnDemandCloseAfter for a specific path  causes a segfault/panic. This issue started with  v1.2.0 and was not an issue with  v1.1.1.

## Describe how to replicate the issue

1. Set runOnDemandStartTimeout and/or runOnDemandCloseAfter for a specific path
2. start server

```
MTX_PATHS_MYPATH_RUNONDEMANDSTARTTIMEOUT=30s ./mediamtx 
```

## Did you attach the server logs?

yes 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16aeb7a]

goroutine 1 [running]:
github.com/bluenviron/mediamtx/internal/conf.(*StringDuration).UnmarshalJSON(0x0, {0xc0003748a0, 0x5, 0x8})
	/s/internal/conf/string_duration.go:28 +0x9a
github.com/bluenviron/mediamtx/internal/conf.(*StringDuration).UnmarshalEnv(0x19cc2a0?, {0xc000590158?, 0xc00016b7a0?}, {0xc000042089?, 0x0?})
	/s/internal/conf/string_duration.go:35 +0x5d
github.com/bluenviron/mediamtx/internal/conf/env.loadEnvInternal(0xc00013bd40?, {0xc00016b7a0, 0x28}, {0x19effe0?, 0xc0002d5380?, 0xc00003b998?})
	/s/internal/conf/env/env.go:33 +0x1202
github.com/bluenviron/mediamtx/internal/conf/env.loadEnvInternal(0xc00013bd40?, {0xc000374400, 0x10}, {0xc0000b3440?, 0xc0002d5180?, 0xc00058fd90?})
	/s/internal/conf/env/env.go:164 +0x1eb5
github.com/bluenviron/mediamtx/internal/conf/env.loadEnvInternal(0xc0000b3440?, {0xc000374400, 0x10}, {0xc00013bd40?, 0xc0002d5180?, 0x22d7f80?})
	/s/internal/conf/env/env.go:28 +0x12ef
github.com/bluenviron/mediamtx/internal/conf/env.Load({0xc000374400, 0x10}, {0xc0000b3440?, 0xc0002d5180})
	/s/internal/conf/env/env.go:224 +0x237
github.com/bluenviron/mediamtx/internal/conf.(*OptionalPath).UnmarshalEnv(0xc0002f2430?, {0xc000374400?, 0x10?}, {0x10?, 0x1978c5e?})
	/s/internal/conf/optional_path.go:64 +0x85
github.com/bluenviron/mediamtx/internal/conf/env.loadEnvInternal(0x19fb660?, {0xc000374400, 0x10}, {0x19efde0?, 0xc0002f2430?, 0xc0005907f0?})
	/s/internal/conf/env/env.go:38 +0x13a4
github.com/bluenviron/mediamtx/internal/conf/env.loadEnvInternal(0x19efde0?, {0xc000374400, 0x10}, {0x19fb660?, 0xc0002f2430?, 0xc00004206a?})
	/s/internal/conf/env/env.go:28 +0x12ef
github.com/bluenviron/mediamtx/internal/conf/env.loadEnvInternal(0x19ca380?, {0xc0003743e5, 0x9}, {0xc0000b3300?, 0xc00015ef40?, 0x1067d39?})
	/s/internal/conf/env/env.go:146 +0x19dd
github.com/bluenviron/mediamtx/internal/conf/env.loadEnvInternal(0x1af4880?, {0xc0003743e5, 0x9}, {0x19ca380?, 0xc00015ef40?, 0xc0003743e0?})
	/s/internal/conf/env/env.go:28 +0x12ef
github.com/bluenviron/mediamtx/internal/conf/env.loadEnvInternal(0x1af4880?, {0x1af6d24, 0x3}, {0x1a99940?, 0xc00015e800?, 0x195ad00?})
	/s/internal/conf/env/env.go:164 +0x1eb5
github.com/bluenviron/mediamtx/internal/conf/env.loadEnvInternal(0x1a99940?, {0x1af6d24, 0x3}, {0x1af4880?, 0xc00015e800?, 0xc0001b6d18?})
	/s/internal/conf/env/env.go:28 +0x12ef
github.com/bluenviron/mediamtx/internal/conf/env.Load({0x1af6d24, 0x3}, {0x1a99940?, 0xc00015e800})
	/s/internal/conf/env/env.go:224 +0x237
github.com/bluenviron/mediamtx/internal/conf.Load({0x0, 0x0}, {0x22c5120, 0x5, 0x5})
	/s/internal/conf/conf.go:262 +0xb7
github.com/bluenviron/mediamtx/internal/core.New({0xc0000a01e0, 0x0, 0x0})
	/s/internal/core/core.go:138 +0x365
main.main()
	/s/main.go:11 +0x52
```

## Did you attach a network dump?

 no

**Comment by aler9** [comment]
Thanks for reporting the issue, this is fixed by #2529

**Comment by aler9** [comment]
added in v1.2.1

**Comment by mrlt8** [comment]
@aler9 Is there a replacement for the deprecated settings?

I'm still getting some panics related to onDemand:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc76783]

goroutine 11 [running]:
github.com/bluenviron/mediamtx/internal/core.(*path).onDemandPublisherStop(0xc00001e3c0, {0xebeec8, 0x14})
	/s/internal/core/path.go:869 +0x143
github.com/bluenviron/mediamtx/internal/core.(*path).doOnDemandPublisherCloseTimer(...)
	/s/internal/core/path.go:504
github.com/bluenviron/mediamtx/internal/core.(*path).runInner(0xc00001e3c0)
	/s/internal/core/path.go:405 +0x653
github.com/bluenviron/mediamtx/internal/core.(*path).run(0xc00001e3c0)
	/s/internal/core/path.go:334 +0x325
created by github.com/bluenviron/mediamtx/internal/core.newPath in goroutine 1
	/s/internal/core/path.go:284 +0x676
```

**Comment by aler9** [comment]
@mrlt8 open another issue and provide details on how to replicate the new, unrelated crash.
