### ISSUE TITLE
Change response API for get config

### ISSUE THREAD

**Issue by mstee1** [bluenviron/mediamtx#2535]
## Describe the feature

Description

Please contact me at the address

```
http://localhost:9997/v3/config/paths/list
```

add the "name" field to the config.

Was:
```
{
    "itemCount": 2,
    "pageCount": 1,
    "items": [
        null,
        {
        "source": "rtsp://login:pass@host:port/path1",
        "maxReaders": 0,
        "sourceProtocol": "tcp"
        },
    ]
}
```
Became:
```
{
    "itemCount": 2,
    "pageCount": 1,
    "items": [
        null,
        {
        "name": "path1",
        "source": "rtsp://login:pass@host:port/path1",
        "maxReaders": 0,
        "sourceProtocol": "tcp"
        },
    ]
}
```
Without this change, it is not possible to correlate responses to the following addresses:
```
http://localhost:9997/v3/paths/list
http://localhost:9997/v3/config/paths/list
```

**Comment by pikachu937** [comment]
Hello.
I support, you **need** to add a **name** (it was there in previous API).
Also, if you go to
```
http://10.100.100.229:9997/v3/config/paths/get/all_others
```

I get null in response, but I should probably get a list of paths that should have been published through all_paths

**Comment by aler9** [comment]
Hello, sorry for this situation, it was a collateral effect of the new path/replace API, that was introduced for supporting the new `pathDefaults` setting, that was introduced for propagating the default configuration to all paths.

**Comment by aler9** [comment]
fixed with #2595 and #2596

**Comment by aler9** [comment]
added in v1.2.1

**Comment by pikachu937** [comment]
Editing the API did not give the desired result. I still don’t receive information on the stream. I push stream 12345678901234567890, when requesting 
```
http://localhost:9997/v3/paths/list
```
I see it on the server:
```
{
    "itemCount": 1,
    "pageCount": 1,
    "items": [
        {
            "name": "12345678901234567890",
            "confName": "all_others",
            "source": {
                "type": "rtspSession",
                "id": "0d496f66-1c4f-48c2-9c7e-07ba7d871cee"
            },
            "ready": true,
            "readyTime": "2023-10-28T22:59:54.693985524+03:00",
            "tracks": [
                "H264"
            ],
            "bytesReceived": 155591,
            "readers": []
        },
}
```
But there is no way to view information on it. When requesting 
```
http://localhost:9997/v3/config/paths/get/12345678901234567890
```
I get the response:
```
{
    "error":"path configuration not found"
}
```
and when requesting
```
http://localhost:9997/v3/config/paths/get/all_others
```
I only get this:
```
{
    "name": "all_others",
    "source": "publisher",
    "sourceFingerprint": "",
    "sourceOnDemand": false,
    "sourceOnDemandStartTimeout": "10s",
    "sourceOnDemandCloseAfter": "10s",
    "maxReaders": 0,
    "srtReadPassphrase": "",
    "record": false,
    "recordPath": "[/mnt/recordings/%path/%Y-%m-%d/%path-%f](http://localhost:9997/mnt/recordings/%path/%Y-%m-%d/%path-%f)",
    "recordFormat": "mpegts",
    "recordPartDuration": "100ms",
    "recordSegmentDuration": "30s",
    "recordDeleteAfter": "2h0m0s",
    "publishUser": "",
    "publishPass": "",
    "publishIPs": [],
    "readUser": "",
    "readPass": "",
    "readIPs": [],
    "overridePublisher": false,
    "fallback": "",
    "srtPublishPassphrase": "",
    "sourceProtocol": "automatic",
    "sourceAnyPortEnable": false,
    "rtspRangeType": "",
    "rtspRangeStart": "",
    "sourceRedirect": "",
    "rpiCameraCamID": 0,
    "rpiCameraWidth": 1920,
    "rpiCameraHeight": 1080,
    "rpiCameraHFlip": false,
    "rpiCameraVFlip": false,
    "rpiCameraBrightness": 0,
    "rpiCameraContrast": 1,
    "rpiCameraSaturation": 1,
    "rpiCameraSharpness": 1,
    "rpiCameraExposure": "normal",
    "rpiCameraAWB": "auto",
    "rpiCameraDenoise": "off",
    "rpiCameraShutter": 0,
    "rpiCameraMetering": "centre",
    "rpiCameraGain": 0,
    "rpiCameraEV": 0,
    "rpiCameraROI": "",
    "rpiCameraHDR": false,
    "rpiCameraTuningFile": "",
    "rpiCameraMode": "",
    "rpiCameraFPS": 30,
    "rpiCameraIDRPeriod": 60,
    "rpiCameraBitrate": 1000000,
    "rpiCameraProfile": "main",
    "rpiCameraLevel": "4.1",
    "rpiCameraAfMode": "auto",
    "rpiCameraAfRange": "normal",
    "rpiCameraAfSpeed": "normal",
    "rpiCameraLensPosition": 0,
    "rpiCameraAfWindow": "",
    "rpiCameraTextOverlayEnable": false,
    "rpiCameraTextOverlay": "%Y-%m-%d %H:%M:%S - MediaMTX",
    "runOnInit": "",
    "runOnInitRestart": false,
    "runOnDemand": "",
    "runOnDemandRestart": false,
    "runOnDemandStartTimeout": "10s",
    "runOnDemandCloseAfter": "10s",
    "runOnReady": "",
    "runOnReadyRestart": false,
    "runOnNotReady": "",
    "runOnRead": "",
    "runOnReadRestart": false,
    "runOnUnread": "",
    "runOnRecordSegmentCreate": "sh -c 'echo $MTX_PATH\" Create\" >> /etc/rss/mtx/$MTX_PATH.log'",
    "runOnRecordSegmentComplete": "sh -c 'echo $MTX_PATH\" Complite\" >> /etc/rss/mtx/$MTX_PATH.log'"
}
```

how i can view full information about stream 12345678901234567890

**Comment by pikachu937** [comment]
> fixed with #2595 and #2596

Editing the API did not give the desired result. I still don’t receive information on the stream. I push stream 12345678901234567890, when requesting 
```
http://localhost:9997/v3/paths/list
```
I see it on the server:
```
{
    "itemCount": 1,
    "pageCount": 1,
    "items": [
        {
            "name": "12345678901234567890",
            "confName": "all_others",
            "source": {
                "type": "rtspSession",
                "id": "0d496f66-1c4f-48c2-9c7e-07ba7d871cee"
            },
            "ready": true,
            "readyTime": "2023-10-28T22:59:54.693985524+03:00",
            "tracks": [
                "H264"
            ],
            "bytesReceived": 155591,
            "readers": []
        },
}
```
But there is no way to view information on it. When requesting 
```
http://localhost:9997/v3/config/paths/get/12345678901234567890
```
I get the response:
```
{
    "error":"path configuration not found"
}
```
and when requesting
```
http://localhost:9997/v3/config/paths/get/all_others
```
I only get this:
```
{
    "name": "all_others",
    "source": "publisher",
    "sourceFingerprint": "",
    "sourceOnDemand": false,
    "sourceOnDemandStartTimeout": "10s",
    "sourceOnDemandCloseAfter": "10s",
    "maxReaders": 0,
    "srtReadPassphrase": "",
    "record": false,
    "recordPath": "[/mnt/recordings/%path/%Y-%m-%d/%path-%f](http://localhost:9997/mnt/recordings/%path/%Y-%m-%d/%path-%f)",
    "recordFormat": "mpegts",
    "recordPartDuration": "100ms",
    "recordSegmentDuration": "30s",
    "recordDeleteAfter": "2h0m0s",
    "publishUser": "",
    "publishPass": "",
    "publishIPs": [],
    "readUser": "",
    "readPass": "",
    "readIPs": [],
    "overridePublisher": false,
    "fallback": "",
    "srtPublishPassphrase": "",
    "sourceProtocol": "automatic",
    "sourceAnyPortEnable": false,
    "rtspRangeType": "",
    "rtspRangeStart": "",
    "sourceRedirect": "",
    "rpiCameraCamID": 0,
    "rpiCameraWidth": 1920,
    "rpiCameraHeight": 1080,
    "rpiCameraHFlip": false,
    "rpiCameraVFlip": false,
    "rpiCameraBrightness": 0,
    "rpiCameraContrast": 1,
    "rpiCameraSaturation": 1,
    "rpiCameraSharpness": 1,
    "rpiCameraExposure": "normal",
    "rpiCameraAWB": "auto",
    "rpiCameraDenoise": "off",
    "rpiCameraShutter": 0,
    "rpiCameraMetering": "centre",
    "rpiCameraGain": 0,
    "rpiCameraEV": 0,
    "rpiCameraROI": "",
    "rpiCameraHDR": false,
    "rpiCameraTuningFile": "",
    "rpiCameraMode": "",
    "rpiCameraFPS": 30,
    "rpiCameraIDRPeriod": 60,
    "rpiCameraBitrate": 1000000,
    "rpiCameraProfile": "main",
    "rpiCameraLevel": "4.1",
    "rpiCameraAfMode": "auto",
    "rpiCameraAfRange": "normal",
    "rpiCameraAfSpeed": "normal",
    "rpiCameraLensPosition": 0,
    "rpiCameraAfWindow": "",
    "rpiCameraTextOverlayEnable": false,
    "rpiCameraTextOverlay": "%Y-%m-%d %H:%M:%S - MediaMTX",
    "runOnInit": "",
    "runOnInitRestart": false,
    "runOnDemand": "",
    "runOnDemandRestart": false,
    "runOnDemandStartTimeout": "10s",
    "runOnDemandCloseAfter": "10s",
    "runOnReady": "",
    "runOnReadyRestart": false,
    "runOnNotReady": "",
    "runOnRead": "",
    "runOnReadRestart": false,
    "runOnUnread": "",
    "runOnRecordSegmentCreate": "sh -c 'echo $MTX_PATH\" Create\" >> /etc/rss/mtx/$MTX_PATH.log'",
    "runOnRecordSegmentComplete": "sh -c 'echo $MTX_PATH\" Complite\" >> /etc/rss/mtx/$MTX_PATH.log'"
}
```

how i can view full information about stream 12345678901234567890

**Comment by aler9** [comment]
@pikachu937 you're confusing "paths" with "path configurations", even if they have similar names. Paths can be accessed through

```
http://localhost:9997/v3/paths/list
http://localhost:9997/v3/paths/get/pathname
```

while path configuration can be accessed through

```
http://localhost:9997/v3/config/paths/list
http://localhost:9997/v3/config/paths/get/pathconfname
```

This is all documented.

**Comment by pikachu937** [comment]
Everything is clear, I just got used to the fact that all the paths and their configurations were previously on one page.

Thank you
