### ISSUE TITLE
invalid SDP Uniview

### ISSUE THREAD

**Issue by pikachu937** [bluenviron/mediamtx#4660]
### Which version are you using?

1.12.2

### Which operating system are you using?

Linux amd64 standard

### Describe how to replicate the issue

cam model Uniview IPC2122LB-SF28K-A

1. start the server
2. publish with rtsp fail
3. read with rtsp fail

### Server logs

2025/06/23 17:59:02 DEB [path 371392387] [RTSP source] [c->s] OPTIONS rtsp://10.0.8.53:554/live/main RTSP/1.0
CSeq: 1
User-Agent: gortsplib

2025/06/23 17:59:02 DEB [path 371392387] [RTSP source] [s->c] RTSP/1.0 200 OK
CSeq: 1
Public: OPTIONS,DESCRIBE,SETUP,PLAY,PAUSE,TEARDOWN,ANNOUNCE,SET_PARAMETER,GET_PARAMETER

2025/06/23 17:59:02 DEB [path 371392387] [RTSP source] [c->s] DESCRIBE rtsp://10.0.8.53:554/live/main RTSP/1.0
Accept: application/sdp
CSeq: 2
User-Agent: gortsplib

2025/06/23 17:59:02 DEB [path 371392387] [RTSP source] [s->c] RTSP/1.0 401 Unauthorized
CSeq: 2
WWW-Authenticate: Digest realm="c4790503a344",nonce="d809bdf662f8362492f0e04dfeee1751", stale="FALSE"

2025/06/23 17:59:02 DEB [path 371392387] [RTSP source] [c->s] DESCRIBE rtsp://10.0.8.53:554/live/main RTSP/1.0
Accept: application/sdp
Authorization: Digest username="admin", realm="c4790503a344", nonce="d809bdf662f8362492f0e04dfeee1751", uri="rtsp://10.0.8.53:554/live/main", response="f9799ea733c81aa36afc1137214c7c02"
CSeq: 3
User-Agent: gortsplib

2025/06/23 17:59:02 DEB [path 371392387] [RTSP source] [s->c] RTSP/1.0 200 OK
CSeq: 3
Content-Base: rtsp://10.0.8.53:554/live/main
Content-Length: 454
Content-Type: application/sdp

v=0
o=- 1001 1 IN
s=VCP IPC Realtime stream
m=video 0 RTP/AVP 105
c=IN
a=control:rtsp://10.0.8.53/media/video1/video
a=rtpmap:105 H264/90000
a=fmtp:105 profile-level-id=640028; packetization-mode=1; sprop-parameter-sets=Z2QAKKw7UDwBE/LCAAAH0AAA6mEI,aOqPLA==
a=recvonly
m=application 0 RTP/AVP 107
c=IN
a=control:rtsp://10.0.8.53/media/video1/metadata
a=rtpmap:107 vnd.onvif.metadata/90000
a=fmtp:107 DecoderTag=h3c-v3 RTCP=0
a=recvonly

2025/06/23 17:59:02 ERR [path 371392387] [RTSP source] invalid SDP: sdp: invalid syntax `o=- 1001 1 IN `

**Comment by pikachu937** [comment]
it looks very much like this
[sdp: invalid syntax 'o=- 1001 1 IN '](https://github.com/bluenviron/gortsplib/issues/618)

**Comment by pikachu937** [comment]
@aler9 please help, fix it

**Comment by pikachu937** [comment]
@aler9 help please

**Comment by aler9** [comment]
this has been fixed months ago with https://github.com/bluenviron/gortsplib/pull/765

**Comment by pikachu937** [comment]
I saw your fix and was hoping it would work, but I checked version 1.14.0 and still get the same error!

**Comment by aler9** [comment]
@pikachu937 i took the SDP you provided in the first post and tested it against the SDP parser in gortsplib/pkg/sdp. If you still have problems, open another bug report and provide a SDP which is actually not working.

**Comment by pikachu937** [comment]
Okay, tomorrow I'll test it on version 1.15.0 and report back.

**Comment by pikachu937** [comment]
I decided not to wait for tomorrow and checked now, there is an error, I opened a new bug report [5008](https://github.com/bluenviron/mediamtx/issues/5008)
