### ISSUE TITLE
Issue with gortsplib bump to 5.1.0 commit causing blackouts in VRChat video players

### ISSUE THREAD

**Issue by iPixelGalaxy** [bluenviron/mediamtx#5090]
### Which version are you using?

ab5574b

### Which operating system are you using?

Linux amd64 standard

### Describe the issue

Since commit ab5574b (bump github.com/bluenviron/gortsplib/v5 from 5.0.1 to 5.1.0 (https://github.com/bluenviron/mediamtx/pull/5086)) VRChat Video players are restarting the stream at random, here is a video of the issue with VLC and VRChat showcasing the stream: https://ipixelgalaxy.com/TempFiles/2025-10-14%2000-22-14.mp4

Unrelated: There is also an issue with VRChat players where if there is any packet loss or heavy bandwidth on other users end that the stream will start stuttering until reloaded, I'm unsure if this is VRChat related and have wanted to make a issue regarding it for a while but don't know exactly how to report it. Often times on my local network it will also stutter after the initial input of the stream until a reload of the video player.

### Describe how to replicate the issue

1. Start MediaMTX
2. Publish with RTMP
3. Read with RTSP (specifically in VRChat it's an issue)

### MediaMTX configuration

[mediamtx.yml](https://github.com/user-attachments/files/22899031/mediamtx.yml)

**Comment by tmatth** [comment]
> ### Which version are you using?
> 
> [ab5574b](https://github.com/bluenviron/mediamtx/commit/ab5574b2b5722bcdfd824ef38422b73da2501af8)
> ### Which operating system are you using?
> 
> Linux arm64 standard
> ### Describe the issue
> 
> Since commit [ab5574b](https://github.com/bluenviron/mediamtx/commit/ab5574b2b5722bcdfd824ef38422b73da2501af8) (bump github.com/bluenviron/gortsplib/v5 from 5.0.1 to 5.1.0 ([#5086](https://github.com/bluenviron/mediamtx/pull/5086))) VRChat Video players are restarting the stream at random, here is a video of the issue with VLC and VRChat showcasing the stream: https://ipixelgalaxy.com/TempFiles/2025-10-14%2000-22-14.mp4

This sounds like it's due to the new timeout functionality in https://github.com/bluenviron/gortsplib/pull/912

> 
> Unrelated: There is also an issue with VRChat players where if there is any packet loss or heavy bandwidth on other users end that the stream will start stuttering until reloaded, I'm unsure if this is VRChat related and have wanted to make a issue regarding it for a while but don't know exactly how to report it. Often times on my local network it will also stutter after the initial input of the stream until a reload of the video player.

This is a separate bug that I believe I've also observed since updating to mediamtx v1.14.0, which updated gortsplib to v4.15.0. My best guess is that it's a consequence of https://github.com/bluenviron/gortsplib/pull/803 but I haven't 100% confirmed that yet.

**Comment by tmatth** [comment]
> This is a separate bug that I believe I've also observed since updating to mediamtx v1.14.0, which updated gortsplib to v4.15.0. My best guess is that it's a consequence of [bluenviron/gortsplib#803](https://github.com/bluenviron/gortsplib/pull/803) but I haven't 100% confirmed that yet.

Sorry this is unrelated to [bluenviron/gortsplib#803](https://github.com/bluenviron/gortsplib/pull/803), it's due to the rtpreorderer, I had to comment out the reordering to avoid the stuttering:
https://github.com/tmatth/gortsplib/commit/3e50d04906ecccf286008be651cd3e369cdf1846

**Comment by iPixelGalaxy** [comment]
> > This is a separate bug that I believe I've also observed since updating to mediamtx v1.14.0, which updated gortsplib to v4.15.0. My best guess is that it's a consequence of [bluenviron/gortsplib#803](https://github.com/bluenviron/gortsplib/pull/803) but I haven't 100% confirmed that yet.
> 
> Sorry this is unrelated to [bluenviron/gortsplib#803](https://github.com/bluenviron/gortsplib/pull/803), it's due to the rtpreorderer, I had to comment out the reordering to avoid the stuttering: [tmatth/gortsplib@3e50d04](https://github.com/tmatth/gortsplib/commit/3e50d04906ecccf286008be651cd3e369cdf1846)

Oh, interesting information, is there anything else I need to provide or is this stuff that is going be looked at whenever there is time
I also wanted to mention I accidentally picked the wrong architecture when I first made the issue, I'm using this on an x64 system rather than arm.

**Comment by ceraso-42** [comment]
Related: I can confirm this behavior on USharpVideo v1.0.1 and was about to submit an issue with our details in triaging it during a mission critical stream (version rollback). Saw this issue right when I went to hit submit. 🫠 

This seems like what's wrong and picks up another issue I'm interested in fixing, so sign me up.

I'm not super up to speed-- what is the newest version number that isn't affected, until there's a fix? We rolled back to 1.12.3 for the time being, and I don't know if we're missing any critical bug fixes being so far back.

**Comment by McHauge** [comment]
can confirm we still have this issue as well on the new v1.15.3 from today

**Comment by turtledude01** [comment]
I have heavily bug tested this issue and found far more details here: #5127 

Basic gist: The timeout is 60 seconds, Windows Media Framework is sending the keep-alive at *EXACTLY* 60 seconds, where as VLC and others send it 5-30 seconds early.

**Comment by killerbigpoint** [comment]
Have the same issue too. Needed to downgrade at the moment

**Comment by aler9** [comment]
thanks @turtledude01 for debugging the issue and linking it back to Windows Media Foundation. This is fixed by https://github.com/bluenviron/gortsplib/pull/932

**Comment by McHauge** [comment]
Hi, I have been testing the master version of MediaMTX today, with a pull of it from the morning (1sh nov 2025). and idk, I still get disconects on it every 1-3 min for like 1-3 sec the the inworld mediaplayer re-tires connects and continues in that loop. so im not sure if this is the full solution compared to rolling back to before 1.15.X versions

This here is the only log I get in MediaMTX when in normal mode about it disconecting my VRC client: 

<img width="910" height="36" alt="Image" src="https://github.com/user-attachments/assets/b6186bb9-c374-43ef-953c-b82316586f9d" />

and here from in vrc about the same event (sorry for the VR image): 

<img width="991" height="443" alt="Image" src="https://github.com/user-attachments/assets/097a23bb-a152-4098-b68a-bf08150952d0" />

**Comment by iPixelGalaxy** [comment]
@McHauge the commit for the fix doesn’t appear to have been merged yet

**Comment by McHauge** [comment]
Ahh sorry, I read it as it had been merged on the master 4 days ago when the rtsp module for updated xD sorry then, my bad

**Comment by McHauge** [comment]
Can confirm on MediaMTX 1.15.4, this is now working correctly for us 👍
