### ISSUE TITLE
Error when record video h265 and use mode useAbsoluteTimestamp True

### ISSUE THREAD

**Issue by ThorPham** [bluenviron/mediamtx#5116]
### Which version are you using?

lastest

### Which operating system are you using?

Linux arm64 Docker

### Describe the issue

I record video from rtsp. its work fine when i use h264 stream but i switch to h265 error " invalid DeltaPocS0". 

### Describe how to replicate the issue

RTSP stream h265 and record video with useAbsoluteTimestamp True.

### MediaMTX logs

Log in mediamtx :
mediamtx  | 2025/10/21 02:34:08 ERR [path fake-ntp2] [recorder] invalid DeltaPocS0
mediamtx  | 2025/10/21 02:34:08 ERR [path fake-ntp1] [recorder] invalid DeltaPocS0
mediamtx  | 2025/10/21 02:34:08 ERR [path fake-ntp3] [recorder] invalid DeltaPocS0
mediamtx  | 2025/10/21 02:34:08 ERR [path fake-ntp4] [recorder] invalid DeltaPocS0
mediamtx  | 2025/10/21 02:34:08 ERR [path fake-ntp2] [recorder] invalid DeltaPocS0
mediamtx  | 2025/10/21 02:34:08 ERR [path fake-ntp1] [recorder] invalid DeltaPocS0
mediamtx  | 2025/10/21 02:34:08 ERR [path fake-ntp3] [recorder] invalid DeltaPocS0
mediamtx  | 2025/10/21 02:34:08 ERR [path fake-ntp4] [recorder] invalid DeltaPocS0

**Comment by dan-nicholls** [comment]
Can you provide us with the debug logs by setting `logLevel: debug` in your config

**Comment by aler9** [comment]
In order to solve this issue, you need to provide a network dump, that can be generated in this way:

1. Download wireshark (https://www.wireshark.org/)
2. Start capturing on the interface used for exchanging packets * If the server and the external hardware or software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card.
3. Start the server and replicate the issue
4. Stop capturing, save the result in .pcap format
5. Attach

**Comment by haselbeckdavid** [comment]
Did anyone know how to solve this issue regarding H265 - was working fine on version 12

  ERR [path cam11] [recorder] invalid DeltaPocS0
  ERR [HLS] [muxer cam11] muxer error: unable to extract DTS: invalid DeltaPocS0
  INF [path cam11] [recorder] recording 1 track (H265)
  ERR [path cam11] [recorder] invalid DeltaPocS0
  ...

  Root cause: MediaMTX starts recording → hits H.265 bitstream parse error (DeltaPocS0 = picture-order-count field in HEVC slice headers) → kills the segment → restarts →
  fails again. Infinite loop, zero bytes written.

**Comment by aler9** [comment]
Closed since author didn't provide required data.

**Comment by RamyMakram** [comment]
Is there is any update for this issue. Because its apeared for me when record camera using h265 encode @aler9 @dan-nicholls

**Comment by dan-nicholls** [comment]
@RamyMakram please attach the packet capture data requested by @aler9, and the debug logs for mediamtx using `logLevel: debug` in your config.

**Comment by aler9** [comment]
@dan-nicholls this is probably solved by https://github.com/bluenviron/mediacommon/pull/371, you can either download MediaMTX source code, upgrade mediacommon and compile or alternatively you can wait for the next release.

**Comment by RamyMakram** [comment]
[here](url) is @dan-nicholls @aler9 
`
2026/09/15 14:57:44 INF MediaMTX v1.19.0, windows, amd64
2026/09/15 14:57:44 INF configuration loaded from C:\AINXPublish\V08092026\tools\mediamtx\windows-amd64\mediamtx.yml
2026/09/15 14:57:44 DEB path manager created
2026/09/15 14:57:44 INF [RTSP] started with listeners on :8554 (TCP/RTSP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2026/09/15 14:57:44 INF [RTMP] started with listener on :1935 (TCP/RTMP)
2026/09/15 14:57:44 INF [HLS] started with listener on :8888 (TCP/HTTP)
2026/09/15 14:57:44 INF [WebRTC] started with listeners on :8889 (TCP/HTTP), :8189 (UDP/ICE)
2026/09/15 14:57:44 INF [SRT] started with listener on :8890 (UDP/SRT)
2026/09/15 14:57:44 INF [MoQ] started with listeners on :8892 (TCP/HTTPS2), :8892 (UDP/HTTP3)
2026/09/15 14:57:44 INF [API] started with listener on :9997 (TCP/HTTP)
2026/09/15 14:58:21 DEB [API] [conn [::1]:57127] [c->s] GET /v3/config/paths/list HTTP/1.1
Host: localhost:9997
Accept: application/json
Authorization: Basic YWlueDphaW54LWxvY2FsLWFwaQ==


2026/09/15 14:58:21 DEB [API] [conn [::1]:57127] [s->c] HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Server: mediamtx

(body of 40 bytes)
2026/09/15 14:58:21 DEB [API] [conn [::1]:57127] [c->s] POST /v3/config/paths/add/camera-1 HTTP/1.1
Host: localhost:9997
Accept: application/json
Authorization: Basic YWlueDphaW54LWxvY2FsLWFwaQ==
Content-Length: 374
Content-Type: application/json; charset=utf-8

{"source":"rtsp://service:Admin!123@192.168.31.254/rtsp_tunnel?p=0\u0026inst=2\u0026h26x=5","sourceOnDemand":false,"runOnInit":"","runOnInitRestart":false,"runOnDemand":"","runOnDemandRestart":false,"rtspTransport":"tcp","record":true,"recordPath":"C:/RecordingCamera/%path/%Y-%m-%d_%H-%M-%S-%f","recordFormat":"fmp4","recordPartDuration":"1s","recordSegmentDuration":"60m"}
2026/09/15 14:58:21 INF reloading configuration (API request)
2026/09/15 14:58:21 DEB [API] [conn [::1]:57127] [s->c] HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Server: mediamtx

(body of 15 bytes)
2026/09/15 14:58:21 DEB [path camera-1] created
2026/09/15 14:58:21 INF [path camera-1] [RTSP source] started
2026/09/15 14:58:21 DEB [API] [conn [::1]:57127] [c->s] POST /v3/config/paths/add/camera-2 HTTP/1.1
Host: localhost:9997
Accept: application/json
Authorization: Basic YWlueDphaW54LWxvY2FsLWFwaQ==
Content-Length: 373
Content-Type: application/json; charset=utf-8

{"source":"rtsp://service:Admin!123@192.168.31.123/rtsp_tunnel?p=0\u0026h26x=4\u0026vcd=2","sourceOnDemand":false,"runOnInit":"","runOnInitRestart":false,"runOnDemand":"","runOnDemandRestart":false,"rtspTransport":"tcp","record":true,"recordPath":"C:/RecordingCamera/%path/%Y-%m-%d_%H-%M-%S-%f","recordFormat":"fmp4","recordPartDuration":"1s","recordSegmentDuration":"60m"}
2026/09/15 14:58:21 DEB [path camera-1] [RTSP source] connecting
2026/09/15 14:58:22 INF reloading configuration (API request)
2026/09/15 14:58:22 DEB [API] [conn [::1]:57127] [s->c] HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Server: mediamtx

(body of 15 bytes)


2026/09/15 14:58:22 DEB [API] [conn [::1]:57127] [c->s] GET /v3/paths/list HTTP/1.1
Host: localhost:9997
Accept: application/json
Authorization: Basic YWlueDphaW54LWxvY2FsLWFwaQ==


2026/09/15 14:58:22 DEB [path camera-1] [RTSP source] [s->c] RTSP/1.0 401 Unauthorized
CSeq: 1
WWW-Authenticate: Digest realm="Please log in with a valid username",nonce="091708ac7fe7046847626b661da85d48",opaque="",stale=FALSE,algorithm=MD5


2026/09/15 14:58:22 DEB [API] [conn [::1]:57127] [s->c] HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Server: mediamtx

(body of 701 bytes)
2026/09/15 14:58:22 DEB [path camera-1] [RTSP source] [c->s] OPTIONS rtsp://192.168.31.254/rtsp_tunnel?p=0&inst=2&h26x=5 RTSP/1.0
Authorization: Digest username="service", realm="Please log in with a valid username", nonce="091708ac7fe7046847626b661da85d48", uri="rtsp://192.168.31.254/rtsp_tunnel?p=0&inst=2&h26x=5", response="0b84039e1ac2bc9b281faa29b4b8332b", algorithm="MD5"
CSeq: 2
User-Agent: gortsplib


2026/09/15 14:58:22 DEB [path camera-1] [RTSP source] [s->c] RTSP/1.0 200 OK
CSeq: 2
Public: DESCRIBE, SETUP, TEARDOWN, PLAY, SET_PARAMETER, GET_PARAMETER, PAUSE


2026/09/15 14:58:22 DEB [path camera-1] [RTSP source] [c->s] DESCRIBE rtsp://192.168.31.254/rtsp_tunnel?p=0&inst=2&h26x=5 RTSP/1.0
Accept: application/sdp
Authorization: Digest username="service", realm="Please log in with a valid username", nonce="091708ac7fe7046847626b661da85d48", uri="rtsp://192.168.31.254/rtsp_tunnel?p=0&inst=2&h26x=5", response="3c9e85ce472eff1dceb48726f5d32778", algorithm="MD5"
CSeq: 3
User-Agent: gortsplib



2026/09/15 14:58:22 DEB [path camera-1] [RTSP source] [s->c] RTSP/1.0 200 OK
CSeq: 3
Cache-Control: no-cache
Content-Base: rtsp://192.168.31.254/rtsp_tunnel
Content-Length: 435
Content-Type: application/sdp

v=0
o=- 0 0 IN IP4 192.168.31.254
s=LIVE VIEW
c=IN IP4 0.0.0.0
t=0 0
a=control:rtsp://192.168.31.254/rtsp_tunnel?p=0&inst=2&h26x=5
m=video 0 RTP/AVP 102
a=rtpmap:102 H265/90000
a=control:rtsp://192.168.31.254/rtsp_tunnel?p=0&inst=2&h26x=5&stream=video
a=recvonly
a=fmtp:102 profile-id=3;sprop-vps=QAEMA///AWAAAAMAgAAAAwAAAwBdAAC94Eg=;sprop-sps=QgEDAWAAAAMAgAAAAwAAAwBdAACgBgIBsWNvfdqbu5L9gLcBDQEAgA==;sprop-pps=RAHBLKwnCBGZ

2026/09/15 14:58:22 DEB [path camera-1] [RTSP source] [c->s] SETUP rtsp://192.168.31.254/rtsp_tunnel?p=0&inst=2&h26x=5&stream=video RTSP/1.0
Authorization: Digest username="service", realm="Please log in with a valid username", nonce="091708ac7fe7046847626b661da85d48", uri="rtsp://192.168.31.254/rtsp_tunnel?p=0&inst=2&h26x=5&stream=video", response="a5a2d09afff276022de2b9da642524d3", algorithm="MD5"
CSeq: 4
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
User-Agent: gortsplib


2026/09/15 14:58:22 DEB [path camera-1] [RTSP source] [s->c] RTSP/1.0 200 OK
CSeq: 4
Session: 1234489364b235b;timeout=30
Transport: RTP/AVP/TCP;unicast;interleaved=0-1;ssrc=420e9218


2026/09/15 14:58:22 INF [path camera-1] [recorder] recording 1 track (H265)
2026/09/15 14:58:22 INF [path camera-1] stream is available and online, 1 track (H265)
2026/09/15 14:58:22 DEB [path camera-1] [RTSP source] [c->s] PLAY rtsp://192.168.31.254/rtsp_tunnel?p=0&inst=2&h26x=5 RTSP/1.0
Authorization: Digest username="service", realm="Please log in with a valid username", nonce="091708ac7fe7046847626b661da85d48", uri="rtsp://192.168.31.254/rtsp_tunnel?p=0&inst=2&h26x=5", response="15e76c2c9d5898a9cfc0bd60618930e8", algorithm="MD5"
CSeq: 5
Range: npt=0-
Session: 1234489364b235b
User-Agent: gortsplib


2026/09/15 14:58:22 DEB [path camera-1] [RTSP source] [s->c] RTSP/1.0 200 OK
2026/09/15 14:58:22 ERR [path camera-1] [recorder] invalid DeltaPocS0
2026/09/15 14:58:24 INF [path camera-1] [recorder] recording 1 track (H265)
2026/09/15 14:58:24 ERR [path camera-1] [recorder] invalid DeltaPocS0
2026/09/15 14:58:26 INF [path camera-1] [recorder] recording 1 track (H265)
2026/09/15 14:58:27 ERR [path camera-1] [recorder] invalid DeltaPocS0
2026/09/15 14:58:29 INF [path camera-1] [recorder] recording 1 track (H265)
2026/09/15 14:58:30 ERR [path camera-1] [recorder] invalid DeltaPocS0
2026/09/15 14:58:32 INF [path camera-1] [recorder] recording 1 track (H265)
2026/09/15 14:58:34 ERR [path camera-1] [recorder] invalid DeltaPocS0
2026/09/15 14:58:36 INF [path camera-1] [recorder] recording 1 track (H265)
2026/09/15 14:58:36 ERR [path camera-1] [recorder] invalid DeltaPocS0
2026/09/15 14:58:38 INF [path camera-1] [recorder] recording 1 track (H265)
2026/09/15 14:58:39 ERR [path camera-1] [recorder] invalid DeltaPocS0
2026/09/15 14:58:41 INF [path camera-1] [recorder] recording 1 track (H265)
2026/09/15 14:58:41 ERR [path camera-1] [recorder] invalid DeltaPocS0
2026/09/15 14:58:43 INF [path camera-1] [recorder] recording 1 track (H265)
2026/09/15 14:58:43 ERR [path camera-1] [recorder] invalid DeltaPocS0
2026/09/15 14:58:45 INF [path camera-1] [recorder] recording 1 track (H265)
2026/09/15 14:58:46 ERR [path camera-1] [recorder] invalid DeltaPocS0
2026/09/15 14:58:47 DEB [path camera-1] [RTSP source] [c->s] GET_PARAMETER rtsp://192.168.31.254/rtsp_tunnel?p=0&inst=2&h26x=5 RTSP/1.0
Authorization: Digest username="service", realm="Please log in with a valid username", nonce="091708ac7fe7046847626b661da85d48", uri="rtsp://192.168.31.254/rtsp_tunnel?p=0&inst=2&h26x=5", response="0990b9e96aae089c1712e10f56bc92eb", algorithm="MD5"
CSeq: 6
Session: 1234489364b235b
User-Agent: gortsplib


2026/09/15 14:58:47 DEB [path camera-1] [RTSP source] [s->c] RTSP/1.0 200 OK
CSeq: 6


2026/09/15 14:58:48 INF [path camera-1] [recorder] recording 1 track (H265)
2026/09/15 14:58:48 ERR [path camera-1] [recorder] invalid DeltaPocS0
2026/09/15 14:58:50 INF [path camera-1] [recorder] recording 1 track (H265)
2026/09/15 14:58:51 ERR [path camera-1] [recorder] invalid DeltaPocS0
2026/09/15 14:58:53 INF [path camera-1] [recorder] recording 1 track (H265)
`



Wireshark files:
https://drive.google.com/file/d/1BlqRey78c9nuv0GnQXRRPQE75ksZBYGA/view?usp=sharing, https://drive.google.com/file/d/1t_0Wg_4MKEde4Lg_0IxyBaSuJcyjJIkJ/view?usp=sharing

**Comment by dan-nicholls** [comment]
@RamyMakram can you validate this is still present with the latest [mediacommon](https://github.com/bluenviron/mediacommon) version?

**Comment by RamyMakram** [comment]
Can u please till me how to validate the issue with mediacommon because there isn't any documentation for it @dan-nicholls

**Comment by dan-nicholls** [comment]
@RamyMakram mediamtx has since been updated with the new `mediacommon` changes. Can you please upgrade to [v1.21.1](https://github.com/bluenviron/mediamtx/releases/tag/v1.21.1) and let us know if this persists.
